{
//=========Macro generated from canvas: Canvas_1/Canvas_1
//=========  (Thu May 12 09:48:58 2016) by ROOT version5.34/30
   TCanvas *Canvas_1 = new TCanvas("Canvas_1", "Canvas_1",422,102,1469,827);
   gStyle->SetOptStat(0);
   Canvas_1->Range(-0.125,547.6981,1.125,1327.717);
   Canvas_1->SetFillColor(0);
   Canvas_1->SetBorderMode(0);
   Canvas_1->SetBorderSize(2);
   Canvas_1->SetTickx(1);
   Canvas_1->SetTicky(1);
   Canvas_1->SetFrameLineWidth(2);
   Canvas_1->SetFrameBorderMode(0);
   Canvas_1->SetFrameLineWidth(2);
   Canvas_1->SetFrameBorderMode(0);
   
   TH1F *WCosThetaStar = new TH1F("WCosThetaStar","Alpha4 0.1, Alpha5 0",10,0,1);
   WCosThetaStar->SetBinContent(1,1206);
   WCosThetaStar->SetBinContent(2,1220);
   WCosThetaStar->SetBinContent(3,1126);
   WCosThetaStar->SetBinContent(4,1088);
   WCosThetaStar->SetBinContent(5,1028);
   WCosThetaStar->SetBinContent(6,1078);
   WCosThetaStar->SetBinContent(7,952);
   WCosThetaStar->SetBinContent(8,886);
   WCosThetaStar->SetBinContent(9,762);
   WCosThetaStar->SetBinContent(10,654);
   WCosThetaStar->SetEntries(10000);
   WCosThetaStar->SetStats(0);
   WCosThetaStar->SetFillColor(8);
   WCosThetaStar->SetFillStyle(3005);
   WCosThetaStar->SetLineColor(8);
   WCosThetaStar->SetLineWidth(2);
   WCosThetaStar->SetMarkerStyle(20);
   WCosThetaStar->GetXaxis()->SetNdivisions(505);
   WCosThetaStar->GetXaxis()->SetLabelFont(132);
   WCosThetaStar->GetXaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetXaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetXaxis()->SetTitleFont(132);
   WCosThetaStar->GetYaxis()->SetLabelFont(132);
   WCosThetaStar->GetYaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetYaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetYaxis()->SetTitleFont(132);
   WCosThetaStar->GetZaxis()->SetLabelFont(132);
   WCosThetaStar->GetZaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetZaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetZaxis()->SetTitleFont(132);
   WCosThetaStar->Draw("");
   
   TH1F *WCosThetaStar = new TH1F("WCosThetaStar","Alpha4 0.1, Alpha5 0",10,0,1);
   WCosThetaStar->SetBinContent(1,1157);
   WCosThetaStar->SetBinContent(2,1158);
   WCosThetaStar->SetBinContent(3,1188);
   WCosThetaStar->SetBinContent(4,1122);
   WCosThetaStar->SetBinContent(5,1070);
   WCosThetaStar->SetBinContent(6,985);
   WCosThetaStar->SetBinContent(7,929);
   WCosThetaStar->SetBinContent(8,907);
   WCosThetaStar->SetBinContent(9,779);
   WCosThetaStar->SetBinContent(10,705);
   WCosThetaStar->SetEntries(10000);
   WCosThetaStar->SetStats(0);
   WCosThetaStar->SetFillColor(4);
   WCosThetaStar->SetFillStyle(3006);
   WCosThetaStar->SetLineColor(4);
   WCosThetaStar->SetLineWidth(2);
   WCosThetaStar->SetMarkerStyle(20);
   WCosThetaStar->GetXaxis()->SetNdivisions(505);
   WCosThetaStar->GetXaxis()->SetLabelFont(132);
   WCosThetaStar->GetXaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetXaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetXaxis()->SetTitleFont(132);
   WCosThetaStar->GetYaxis()->SetLabelFont(132);
   WCosThetaStar->GetYaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetYaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetYaxis()->SetTitleFont(132);
   WCosThetaStar->GetZaxis()->SetLabelFont(132);
   WCosThetaStar->GetZaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetZaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetZaxis()->SetTitleFont(132);
   WCosThetaStar->Draw("same");
   
   TPaveText *pt = new TPaveText(0.01,0.945,0.2538908,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(1);
   pt->SetFillColor(0);
   pt->SetLineColor(0);
   pt->SetLineWidth(2);
   pt->SetTextColor(0);
   pt->SetTextFont(132);
   TText *text = pt->AddText("Alpha4 0.1, Alpha5 0");
   pt->Draw();
   
   TH1F *WCosThetaStar = new TH1F("WCosThetaStar","Alpha4 0, Alpha5 0",10,0,1);
   WCosThetaStar->SetBinContent(1,1007);
   WCosThetaStar->SetBinContent(2,1103);
   WCosThetaStar->SetBinContent(3,1105);
   WCosThetaStar->SetBinContent(4,1061);
   WCosThetaStar->SetBinContent(5,1098);
   WCosThetaStar->SetBinContent(6,1011);
   WCosThetaStar->SetBinContent(7,919);
   WCosThetaStar->SetBinContent(8,985);
   WCosThetaStar->SetBinContent(9,903);
   WCosThetaStar->SetBinContent(10,808);
   WCosThetaStar->SetEntries(10000);
   WCosThetaStar->SetStats(0);
   WCosThetaStar->SetFillColor(2);
   WCosThetaStar->SetFillStyle(3004);
   WCosThetaStar->SetLineColor(2);
   WCosThetaStar->SetLineWidth(2);
   WCosThetaStar->SetMarkerStyle(20);
   WCosThetaStar->GetXaxis()->SetNdivisions(505);
   WCosThetaStar->GetXaxis()->SetLabelFont(132);
   WCosThetaStar->GetXaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetXaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetXaxis()->SetTitleFont(132);
   WCosThetaStar->GetYaxis()->SetLabelFont(132);
   WCosThetaStar->GetYaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetYaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetYaxis()->SetTitleFont(132);
   WCosThetaStar->GetZaxis()->SetLabelFont(132);
   WCosThetaStar->GetZaxis()->SetLabelSize(0.03);
   WCosThetaStar->GetZaxis()->SetTitleSize(0.036);
   WCosThetaStar->GetZaxis()->SetTitleFont(132);
   WCosThetaStar->Draw("same");
   
   TLegend *leg = new TLegend(0.5,0.67,0.88,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(132);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("WCosThetaStar","Alpha4 0.1, Alpha5 0","lpf");
   entry->SetFillColor(8);
   entry->SetFillStyle(3005);
   entry->SetLineColor(8);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("WCosThetaStar","Alpha4 0.1, Alpha5 0","lpf");
   entry->SetFillColor(4);
   entry->SetFillStyle(3006);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("WCosThetaStar","Alpha4 0, Alpha5 0","lpf");
   entry->SetFillColor(2);
   entry->SetFillStyle(3004);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   leg->Draw();
   Canvas_1->Modified();
   Canvas_1->cd();
   Canvas_1->SetSelected(Canvas_1);
}
